<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<PackageId>SingleFlight</PackageId>
		<Authors>Adolfok3</Authors>
		<Description>A simple, lightweight, zero-dependency library that stops duplicate concurrent calls: identical in-flight work runs just once and every caller shares the result.</Description>
		<RepositoryUrl>https://github.com/Adolfok3/SingleFlight</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageIcon>icon.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
</Project>
